name: Docker Image CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          -
            name: Login to DockerHub
            uses: docker/login-action@v1 
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
          - 
            uses: docker/build-push-action@v2
            name: Build the Docker image
            with:
              push: true
              tags: herliantodev/project-restobook:latest
          
